### ISSUE TITLE
Entity Placement Bugs

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#135]
1) creeps are bugged, e.g. Depths room #678
2) Gurdy offset needs to be inverted
3) Satan offset needs to be inverted
4) Satan graphic needs to be changed to a statue - however I suggest a modified statue to show that it isn't just a vanilla Devil Statue, maybe like with a red arrow that points to a tiny picture of Satan or something along those lines

@budjmt

**Comment by Zamiell** [comment]
also, as an additional idea, maybe it should show the 2 leeches + the fallen spawn points as part of the devil statue placement

**Comment by budjmt** [comment]
https://github.com/Tempus/Basement-Renovator/pull/136 fixed 1, 2, and 3. As for the last one, I disagree with the statue part since devil statue is also a thing and it could be confusing. I think the current picture is perfectly effective.
As far as bosses showing spawned entity locations, I was asked about that in the context of mom and I assume it'd be extrapolated to Ultra Greed. I'm a bit on the fence about this since it's implemented in different ways. Mom for example has one entity for the foot and another 4 for the doors in her rooms, but ug and satan are just a single entity. I'd lean towards no on this for now since it's extremely case by case.

**Comment by Zamiell** [comment]
ok, sounds reasonable
