### ISSUE TITLE
Doesn't work with Afterbirth

### ISSUE THREAD

**Issue by sillypears** [Tempus/Basement-Renovator#5]
Hi @Tempus,

With all the new room types that were introduced in Afterbirth, I'm not sure if you have any intentions of updating BR, but if you're currently working on it, do you have any kind of ETA on it? Or is there any kind of help you'd like/need to get this working with Afterbirth? I know myself and a few others are looking forward to a new release and would be willing to help out.

Thanks!

**Comment by Zamiell** [comment]
https://www.reddit.com/r/themoddingofisaac/comments/3rcosz/my_tools_are_now_afterbirth_compatible/cwmzvdx

"I was trying to finish it before everyone else got unpacking done actually, but everyone is too fast! It should drop in the next day or two."

This was posted 22 days ago.

When I asked him about it, he posted this 8 days ago:

https://www.reddit.com/r/themoddingofisaac/comments/3rhhqq/a_new_tool_like_basement_renovator/cx3dwsx

"It got stalled between all the patches and my 60 hour work week, just gotta dredge up some motivation to finish it off."

Furthermore, since it looks like he hasn't bothered answering issues or pull requests dating all the way back to February, opening a new issue seems a little futile, but I guess we can still hope.

**Comment by Tempus** [comment]
Well, waaaaaay too much later, I now have afterbirth support.
