### ISSUE TITLE
No support for weighted entities

### ISSUE THREAD

**Issue by Tweevle** [Tempus/Basement-Renovator#58]
If you look in the decompiled room xmls, you can see certain entities placed in rooms are designed to have a weighted chance to be one thing or another - an example is the shop rooms, which are supposed to have a chance to be a restocking machine instead of a donation one. This was a feature discussed by Edmund prior to Rebirth coming out, but it's actually broken in the game at the moment (90% sure it was always broken) and only ever results in one entity being used.

From what I can tell the editor presents this in an odd way by placing all possible entities seperately in the same place. I believe this can potentially cause problems such as a different entity appearing in the game than was originally there (e.g. restock machines appearing in all shops instead of donation machines). It would be good to have support for weighted entities to prevent this behaviour and potentially allow use of this feature in the future if it's is fixed by the devs.

**Comment by Tempus** [comment]
This feature is indeed broken in the game, and throughout my tests was in fact always broken. Indeed, entity weight has been there since Rebirth, but has never actually done anything. The editor currently handles entity weighting by not changing it at all whatsoever, or allowing it to be changed. This should be completely safe - it produces identical entries to the original in the five cases I tested, so hopefully there are no problems.

The support for editing them is there, and can be enabled with a simple patch when and if they decide to actually add this functionality. Until then, I have no plans to clutter the editor with features that do literally nothing.

This issue will be reopened if evidence of a poorly parsed weighted entity situation arises.

**Comment by Strawrat** [comment]
This feature seems to have been fixed in a recent Booster Pack. It works as of Booster #4.

![image](https://user-images.githubusercontent.com/20307416/35131287-298ee564-fcbd-11e7-8adc-f7624defcefb.png)

If you repeatedly go to this Shop (debug console: "goto s.shop.0"), you can see that it sometimes spawns a Restock Machine instead of a Donation Machine (1.0 vs 0.25 weight value).

![image](https://user-images.githubusercontent.com/20307416/35131393-d4d4006c-fcbd-11e7-866e-8a3e6c642e8a.png)

**Comment by Zamiell** [comment]
this feature is already in BR, run it from source
