### ISSUE TITLE
Allow for smaller room weights

### ISSUE THREAD

**Issue by Tweevle** [Tempus/Basement-Renovator#59]
The rare small rooms that exist in the files have a weight of 0.1, which is less than the editor allows. It'd be good to have an option for that, and possibly to set a custom weight/difficulty for fine tuning.

**Comment by Zamiell** [comment]
As Tweevle said, since 0.1 is a valid value in the vanilla game files, it should be present in the list of weights. (And don't forgot to also add 0.1 to the list of weights to search by in the filter.)

An implementation of custom weights could be something like the following: a new element could be added to the weight list called "Custom", and that would open up another sub-menu with a text-input box so that the user can specify exactly what weight they want. Subsequently, a "Custom" weight search filter would also need to be added so that one could easily find all of the custom weight rooms.

**Comment by Tempus** [comment]
Added 0.1 into BR. Custom weight sorting is a wishlist thing that I don't know if it's worth my time at this point. Closed for now.
