### ISSUE TITLE
Visual indicator that a filter is active

### ISSUE THREAD

**Issue by Zamiell** [Tempus/Basement-Renovator#60]
There should be a large, obvious indicator that some sort of room search filter is active.

It is entirely too common for me to go searching for a room and forget that I have an old filter still activated, which causes me to assume that I deleted the room that I was looking for or that Basement Renovator bugged out.

One potential implementation of this would be a big red square with an X that you can click to delete ALL active search filters. If you see the big red X, then it means you have search filters on. Or something along these lines.

**Comment by Tempus** [comment]
I've noticed you do this on stream, and was already thinking about it. I'll certainly be doing something along these lines, though a large red X may not be what I go with because I'd hate to make the window larger if there's a more elegant solution. At the very least, there will be better visual indication and a clear filter hotkey.

**Comment by Tempus** [comment]
Took a lot longer than expected, but this is now added. There are bright red buttons, that will show active filters and clear them when pressed. Ctrl K will also clear all filters.
