### ISSUE TITLE
No room mods work with latest release - possibly due to upcoming afterbirth+

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Tempus/Basement-Renovator#94]
So no mods related to rooms work I am going to guess that something has changed under the hood.

**Comment by Tempus** [comment]
Could you provide more details? The steam copy of BoI shows no updates, and there are no posts about this on the modding subreddit. Also, I can currently use mods involving rooms on my computer (including ones I did not make myself).

Basically - unsure what your problem is exactly, cannot reproduce as described.

**Comment by P3rf3ctXZer0** [comment]
Okay hold on I will make a video

**Comment by P3rf3ctXZer0** [comment]
Apologies I had to remove my personal information from clip. So its a bit slower.

**Comment by P3rf3ctXZer0** [comment]
https://www.dropbox.com/s/ntbe466pg2ttcfk/2016-12-10%2000-28-34.flv?dl=0

**Comment by P3rf3ctXZer0** [comment]
that is some bad audio quality

**Comment by P3rf3ctXZer0** [comment]
Here is better visual quality.
https://youtu.be/uisFdvxeXPo

**Comment by Zamiell** [comment]
Video is terrible quality; can't hear you over the music. If this issue still occurs with the forthcoming Afterbirth+ version of Basement Renovator, reopen another issue with an actual detailed text description of the problem and how to reproduce it.
